let categories = [
{
"id":"food",
"icon":"restaurant",
"name":"Food",
"color":"#2693ff",
"type":"expenses"
},{
"id":"bills",
"icon":"receipt",
"name":"Bills",
"color":"#FF0000",
"type":"expenses"
},{
"id":"home",
"icon":"home",
"name":"Home",
"color":"#FF0000",
"type":"expenses"
},{
"id":"transportation",
"icon":"subway",
"name":"Transportation",
"color":"#FF0000",
"type":"expenses"
},{
"id":"car",
"icon":"car-sport",
"name":"Car",
"color":"#FF0000",
"type":"expenses"
},{
"id":"entertainment",
"icon":"game-controller",
"name":"Entertainment",
"color":"#FF0000",
"type":"expenses"
},{
"id":"shopping",
"icon":"cart",
"name":"Shopping",
"color":"#FF0000",
"type":"expenses"
},{
"id":"clothing",
"icon":"shirt",
"name":"Clothing",
"color":"#FF0000",
"type":"expenses"
},{
"id":"insurance",
"icon":"shield-checkmark",
"name":"Insurance",
"color":"#FF0000",
"type":"expenses"
},{
"id":"tax",
"icon":"reader",
"name":"Tax",
"color":"#FF0000",
"type":"expenses"
},{
"id":"telephone",
"icon":"call",
"name":"Telephone",
"color":"#FF0000",
"type":"expenses"
},{
"id":"health",
"icon":"medkit",
"name":"Health",
"color":"#FF0000",
"type":"expenses"
},{
"id":"sport",
"icon":"reader",
"name":"Sport",
"color":"#FF0000",
"type":"expenses"
},{
"id":"electronics",
"icon":"watch",
"name":"Electronics",
"color":"#FF0000",
"type":"expenses"
},{
"id":"gift",
"icon":"gift",
"name":"Gift",
"color":"#FF0000",
"type":"expenses"
},{
"id":"travel",
"icon":"airplane",
"name":"Travel",
"color":"#FF0000",
"type":"expenses"
},{
"id":"education",
"icon":"school",
"name":"Education",
"color":"#FF0000",
"type":"expenses"
},{
"id":"office",
"icon":"attach",
"name":"Office",
"color":"#FF0000",
"type":"expenses"
},{
"id":"other",
"icon":"grid",
"name":"Other",
"color":"#FF0000",
"type":"both"
},{
"id":"salary",
"icon":"wallet",
"name":"Salary",
"color":"#00FF00",
"type":"income"
},{
"id":"awards",
"icon":"medal",
"name":"Awards",
"color":"#00FF00",
"type":"income"
},{
"id":"sale",
"icon":"pricetag",
"name":"Sale",
"color":"#00FF00",
"type":"income"
}
];

export {categories};